# Generated by Django 4.2.26 on 2025-11-14 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("has_description", models.BooleanField(default=False)),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("width", models.FloatField(default=100)),
                ("height", models.FloatField(default=60)),
                ("shape", models.CharField(default="oval", max_length=20)),
                ("color", models.CharField(default="#E8F4F8", max_length=7)),
                ("border_color", models.CharField(default="#2C3E50", max_length=7)),
                ("text_color", models.CharField(default="#2C3E50", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="pods_app.pod",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "relationship_type",
                    models.CharField(default="default", max_length=50),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("color", models.CharField(default="#34495E", max_length=7)),
                ("line_width", models.IntegerField(default=2)),
                ("arrow", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_source",
                        to="pods_app.pod",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_target",
                        to="pods_app.pod",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
