# Generated by Django 4.2.26 on 2025-11-17 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pods_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pod",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Pod",
                "verbose_name_plural": "Pods",
            },
        ),
        migrations.AlterModelOptions(
            name="relationship",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Relationship",
                "verbose_name_plural": "Relationships",
            },
        ),
        migrations.AlterField(
            model_name="pod",
            name="border_color",
            field=models.CharField(
                default="#2C3E50",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex code (e.g., #FF5733)",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pod",
            name="color",
            field=models.CharField(
                default="#E8F4F8",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex code (e.g., #FF5733)",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="pod",
            name="has_description",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="pod",
            name="height",
            field=models.FloatField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pod",
            name="shape",
            field=models.CharField(
                choices=[("oval", "Oval"), ("rectangle", "Rectangle")],
                default="oval",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pod",
            name="text_color",
            field=models.CharField(
                default="#2C3E50",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex code (e.g., #FF5733)",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pod",
            name="width",
            field=models.FloatField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="color",
            field=models.CharField(
                default="#34495E",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex code (e.g., #FF5733)",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="line_width",
            field=models.IntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="pod",
            index=models.Index(
                fields=["parent", "created_at"], name="pods_app_po_parent__aa2e2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pod",
            index=models.Index(fields=["name"], name="pods_app_po_name_af128b_idx"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["source", "target"], name="pods_app_re_source__8e63b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["created_at"], name="pods_app_re_created_572ae8_idx"
            ),
        ),
    ]
